/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Caio Martins
 */
public class TelaFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form Financeiro
     */
    public TelaFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResultadoFinanceiro = new javax.swing.JPanel();
        scrResultadoFinanceiro = new javax.swing.JScrollPane();
        saidaResultadoFinanceiro = new javax.swing.JTextArea();
        pnlFinanFinanceiro = new javax.swing.JPanel();
        btnCalcularLucroFinanceiro = new javax.swing.JButton();
        btnBalancoMensalFinanceiro = new javax.swing.JToggleButton();
        btnBalancoDiarioFinanceiro = new javax.swing.JToggleButton();
        btnRelatorioDiarioFinanceiro = new javax.swing.JToggleButton();
        btnRelatorioMensalFinanceiro = new javax.swing.JToggleButton();
        btnRegistrarDespesaFinanceiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlResultadoFinanceiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cantarell", 1, 15))); // NOI18N

        saidaResultadoFinanceiro.setColumns(20);
        saidaResultadoFinanceiro.setRows(5);
        scrResultadoFinanceiro.setViewportView(saidaResultadoFinanceiro);

        javax.swing.GroupLayout pnlResultadoFinanceiroLayout = new javax.swing.GroupLayout(pnlResultadoFinanceiro);
        pnlResultadoFinanceiro.setLayout(pnlResultadoFinanceiroLayout);
        pnlResultadoFinanceiroLayout.setHorizontalGroup(
            pnlResultadoFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrResultadoFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultadoFinanceiroLayout.setVerticalGroup(
            pnlResultadoFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoFinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrResultadoFinanceiro)
                .addContainerGap())
        );

        pnlFinanFinanceiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Financeiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cantarell", 1, 15))); // NOI18N

        btnCalcularLucroFinanceiro.setText("Calcular Lucro");
        btnCalcularLucroFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularLucroFinanceiroActionPerformed(evt);
            }
        });

        btnBalancoMensalFinanceiro.setText("Balanço Mensal");
        btnBalancoMensalFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalancoMensalFinanceiroActionPerformed(evt);
            }
        });

        btnBalancoDiarioFinanceiro.setText("Balanço Diário");
        btnBalancoDiarioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalancoDiarioFinanceiroActionPerformed(evt);
            }
        });

        btnRelatorioDiarioFinanceiro.setText("Relatório Diário");
        btnRelatorioDiarioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioDiarioFinanceiroActionPerformed(evt);
            }
        });

        btnRelatorioMensalFinanceiro.setText("Relatório Mensal");
        btnRelatorioMensalFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioMensalFinanceiroActionPerformed(evt);
            }
        });

        btnRegistrarDespesaFinanceiro.setText("Registrar Despesas");
        btnRegistrarDespesaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDespesaFinanceiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFinanFinanceiroLayout = new javax.swing.GroupLayout(pnlFinanFinanceiro);
        pnlFinanFinanceiro.setLayout(pnlFinanFinanceiroLayout);
        pnlFinanFinanceiroLayout.setHorizontalGroup(
            pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanFinanceiroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularLucroFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFinanFinanceiroLayout.createSequentialGroup()
                        .addGroup(pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBalancoDiarioFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRelatorioDiarioFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBalancoMensalFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRelatorioMensalFinanceiro)))
                    .addGroup(pnlFinanFinanceiroLayout.createSequentialGroup()
                        .addComponent(btnRegistrarDespesaFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(34, 34, 34))
        );
        pnlFinanFinanceiroLayout.setVerticalGroup(
            pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanFinanceiroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnCalcularLucroFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBalancoDiarioFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBalancoMensalFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFinanFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioDiarioFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioMensalFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarDespesaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFinanFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResultadoFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFinanFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResultadoFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularLucroFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularLucroFinanceiroActionPerformed

    }//GEN-LAST:event_btnCalcularLucroFinanceiroActionPerformed

    private void btnBalancoMensalFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalancoMensalFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalancoMensalFinanceiroActionPerformed

    private void btnBalancoDiarioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalancoDiarioFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalancoDiarioFinanceiroActionPerformed

    private void btnRelatorioDiarioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioDiarioFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioDiarioFinanceiroActionPerformed

    private void btnRelatorioMensalFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioMensalFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioMensalFinanceiroActionPerformed

    private void btnRegistrarDespesaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDespesaFinanceiroActionPerformed
        new TelaDespesa().setVisible(true);
    }//GEN-LAST:event_btnRegistrarDespesaFinanceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBalancoDiarioFinanceiro;
    private javax.swing.JToggleButton btnBalancoMensalFinanceiro;
    private javax.swing.JButton btnCalcularLucroFinanceiro;
    private javax.swing.JButton btnRegistrarDespesaFinanceiro;
    private javax.swing.JToggleButton btnRelatorioDiarioFinanceiro;
    private javax.swing.JToggleButton btnRelatorioMensalFinanceiro;
    private javax.swing.JPanel pnlFinanFinanceiro;
    private javax.swing.JPanel pnlResultadoFinanceiro;
    private javax.swing.JTextArea saidaResultadoFinanceiro;
    private javax.swing.JScrollPane scrResultadoFinanceiro;
    // End of variables declaration//GEN-END:variables
}
