/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.File;
import javax.swing.JOptionPane;
import trabalhofinal.Administrador;
import trabalhofinal.ControleDeLogin;
import Modelo.Importar_ExportarDadosAdm;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import trabalhofinal.Administrador;

/**
 *
 * @author aluno
 */


public class CadastroAdm extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAdm
     */
    String diretorioAtual = System.getProperty("user.dir");
    String caminhoArquivo = diretorioAtual + File.separator + "DadosProjetoTp1.xlsx";
    Administrador adm;
    public CadastroAdm() {
        
        System.out.println(caminhoArquivo);
        initComponents();
        adm = new Administrador();
        adm = Importar_ExportarDadosAdm.importData(caminhoArquivo);
        
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtNomeAdm.requestFocus();
        txtIdAdm.setText("1");
        txtIdAdm.setEnabled(false);
        
        txtEmailAdm.setText(adm.getEmail());
        txtNomeAdm.setText(adm.getNome());
        txtSenhaAdm.setText(adm.getSenha());
        txtCpfAdm.setText(adm.getCpf());
        txtDataNascimento.setText(adm.getDataNascimento());
        System.out.println(adm.getCpf());
        System.out.println(adm.getDataNascimento());
        System.out.println(adm.getEmail());
        System.out.println(adm.getId());
        System.out.println(adm.getSenha());
    }
    
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNomeAdm = new javax.swing.JTextField();
        lblNomeADm = new javax.swing.JLabel();
        txtIdAdm = new javax.swing.JTextField();
        lblIdAdm = new javax.swing.JLabel();
        txtEmailAdm = new javax.swing.JTextField();
        lblEmailAdm = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblCpfAdm = new javax.swing.JLabel();
        txtCpfAdm = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblSenhaAdm = new javax.swing.JLabel();
        txtSenhaAdm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4213410-arrow-down-download-move-save_115410_1.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4115230-cancel-close-cross-delete_114048_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_modify_icon-icons.com_49882_1.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro do Administrador"));

        txtNomeAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAdmActionPerformed(evt);
            }
        });

        lblNomeADm.setText("Nome:");

        lblIdAdm.setText("ID:");

        lblEmailAdm.setText("Email:");

        lblDataNascimento.setText("Data de Nascimento:");

        lblCpfAdm.setText("CPF:");

        try {
            txtCpfAdm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfAdmActionPerformed(evt);
            }
        });

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblSenhaAdm.setText("Criar Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeADm)
                            .addComponent(lblEmailAdm)
                            .addComponent(lblCpfAdm)
                            .addComponent(lblIdAdm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEmailAdm)
                                .addGap(21, 21, 21))
                            .addComponent(txtCpfAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSenhaAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeADm)
                    .addComponent(txtNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfAdm)
                    .addComponent(txtCpfAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAdm)
                    .addComponent(txtIdAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAdm)
                    .addComponent(txtSenhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addGap(28, 28, 28)
                .addComponent(btnEditar)
                .addGap(28, 28, 28)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAdmActionPerformed
          
    }//GEN-LAST:event_txtNomeAdmActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // habilitando os campos de texto:
        txtNomeAdm.setEnabled(false);
        txtEmailAdm.setEnabled(false);
        txtCpfAdm.setEnabled(false);
        txtIdAdm.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtSenhaAdm.setEnabled(false);
        
        //habilitando os botões:
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        
        //Mostrar dados atuais do adm:
        txtEmailAdm.setText(adm.getEmail());
        txtIdAdm.setText(String.valueOf(adm.getId()));
        txtNomeAdm.setText(adm.getNome());
        txtSenhaAdm.setText(adm.getSenha());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCpfAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfAdmActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        
            if (txtEmailAdm.getText().equals("") || txtIdAdm.getText().equals("") || txtNomeAdm.getText().equals("") || txtSenhaAdm.getPassword().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
            }
            else{
                // pegando as mensagens do campo de texto:
                String nomeAdm = txtNomeAdm.getText();
                String EmailAdm = txtEmailAdm.getText();
                String cpfAdm = txtCpfAdm.getText();
                String IDADm = txtIdAdm.getText();
                String dataNascimento = txtDataNascimento.getText();
                String senhaAdm = String.valueOf(txtSenhaAdm.getPassword());
                
                //passando as menssagens para a classe Administrador:
                
                adm.setNome(nomeAdm);
                adm.setEmail(EmailAdm);
                adm.setCpf(cpfAdm);
                adm.setId(IDADm);
                adm.setDataNascimento(dataNascimento);
                adm.setSenha(senhaAdm);
                
                ControleDeLogin.pegaAdmCpf(adm);
                ControleDeLogin.pegaAdmNome(adm);
                ControleDeLogin.pegaAdmSenha(adm);
                
                //deixando as menssagens salvas nos campos:
                txtNomeAdm.setEnabled(false);
                txtEmailAdm.setEnabled(false);
                txtCpfAdm.setEnabled(false);
                txtIdAdm.setEnabled(false);
                txtDataNascimento.setEnabled(false);
                txtSenhaAdm.setEnabled(false);
                
                //habilitando botões:
                btnEditar.setEnabled(true);
                btnSalvar.setEnabled(false);
                
                JOptionPane.showMessageDialog(null, "Administrador cadastrado com sucesso!");
                
                try {
                    Importar_ExportarDadosAdm.exportDataAdm(caminhoArquivo, adm);
                } catch (IOException ex) {
                    Logger.getLogger(CadastroAdm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
              
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // habilitando os campos de texto:
        txtNomeAdm.setEnabled(true);
        txtEmailAdm.setEnabled(true);
        txtCpfAdm.setEnabled(true);
        txtIdAdm.setEnabled(false);
        txtDataNascimento.setEnabled(true);
        txtSenhaAdm.setEnabled(true);
        
        //habilitando os botões:
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpfAdm;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmailAdm;
    private javax.swing.JLabel lblIdAdm;
    private javax.swing.JLabel lblNomeADm;
    private javax.swing.JLabel lblSenhaAdm;
    private javax.swing.JFormattedTextField txtCpfAdm;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmailAdm;
    private javax.swing.JTextField txtIdAdm;
    private javax.swing.JTextField txtNomeAdm;
    private javax.swing.JPasswordField txtSenhaAdm;
    // End of variables declaration//GEN-END:variables
}
